quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.port=8080
quarkus.http.root-path=/
quarkus.quinoa.build-dir=out
quarkus.quinoa.ui-root-path=/axiom-cda
quarkus.quinoa.dev-server=false
quarkus.quinoa.package-manager-command.build-env.NODE_ENV=production

# Logging
quarkus.log.level=INFO
quarkus.log.category."net.ihe.gazelle.axiomcda".level=DEBUG
