quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.port=8080

# Logging
quarkus.log.level=INFO
quarkus.log.category."net.ihe.gazelle.axiomcda".level=DEBUG
