//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 11:11:31 AM CEST 
//


package net.ihe.gazelle.axiomcda.api.bbr;



import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ValueSetConceptList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueSetConceptList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="concept" type="{}ValueSetConcept"/&gt;
 *           &lt;element name="include" type="{}ValueSetRef"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="exception" type="{}ValueSetConcept" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueSetConceptList", propOrder = {
    "conceptOrInclude",
    "exception"
})
public class ValueSetConceptList implements HasParent {

    @XmlElements({
        @XmlElement(name = "concept", type = ValueSetConcept.class),
        @XmlElement(name = "include", type = ValueSetRef.class)
    })
    private List<Object> conceptOrInclude;
    private List<ValueSetConcept> exception;
    
    @XmlTransient
	private ValueSet parentObject;

    @SuppressWarnings("unchecked")
	public ValueSet getParentObject() {
		return parentObject;
	}

	public void setParentObject(ValueSet parentObject) {
		this.parentObject = parentObject;
	}
	
	void afterUnmarshal( javax.xml.bind.Unmarshaller u, Object parent ){
		this.parentObject = (ValueSet)parent;
	}

    /**
     * Gets the value of the conceptOrInclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conceptOrInclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConceptOrInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetConcept }
     * {@link ValueSetRef }
     * 
     * 
     */
    public List<Object> getConceptOrInclude() {
        if (conceptOrInclude == null) {
            conceptOrInclude = new ArrayList<>();
        }
        return this.conceptOrInclude;
    }

    /**
     * Gets the value of the exception property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exception property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSetConcept }
     * 
     * 
     */
    public List<ValueSetConcept> getException() {
        if (exception == null) {
            exception = new ArrayList<>();
        }
        return this.exception;
    }

}
